### ISSUE TITLE
OAIPMH dc:subject is not being populated with keywords

### ISSUE THREAD

**Issue by kevinpdavies** [geopython/pycsw#339] opened 2015-06-10 05:52 UTC
The dc:subject returned in an OAIPMH ListRecords request is always empty. 

This field is mapped to keywords_csv in Geonode in file:

    geonode/catalogue/backends/pycsw_local_mappings.py

When a keyword is added to a layer, a new tag is created for that keyword and linked to the base record. There is also a django 'content type' stored with this relationship, and it is set to 'layer' (id = 41).

However, when the pycsw/server.py retrieves the keywords using:

    keywords = util.getqattr(recobj, queryables['dc:subject']['dbcol'])

The log file (with DEBUG level) shows the following two queries:

    Wed, 10 Jun 2015 00:30:29] [DEBUG] file=/usr/lib/python2.7/dist-packages/django/db/backends/util.py line=79 module=util function=execute (0.000) SELECT "django_content_type"."id", "django_content_type"."name", "django_content_type"."app_label", "django_content_type"."model" FROM "django_content_type" WHERE ("django_content_type"."model" = 'resourcebase'  AND "django_content_type"."app_label" = 'base' ); args=('resourcebase', u'base')
    Wed, 10 Jun 2015 00:30:29] [DEBUG] file=/usr/lib/python2.7/dist-packages/django/db/backends/util.py line=79 module=util function=execute (0.001) SELECT DISTINCT "taggit_tag"."id", "taggit_tag"."name", "taggit_tag"."slug" FROM "taggit_tag" INNER JOIN "taggit_taggeditem" ON ( "taggit_tag"."id" = "taggit_taggeditem"."tag_id" ) WHERE ("taggit_taggeditem"."object_id" = 1  AND "taggit_taggeditem"."content_type_id" = 38 ) LIMIT 21; args=(1, 38)

The first query seems to be looking for the content_type_id for 'resourcebase' rather than 'layer'. The second query is then retrieving keywords (tags) with a content type ID of '38'.

I can confirm this by changing the 'content type' of the record/tag relationship from 'layer' to 'resource base' through the geonode admin screen. The dc:subject field is then populated as expected.

So changing the 'content type' of the record/tag relationship to 'resource base' fixes the empty dc:subject problem, however, the keywords are no longer visible on the layer page in geonode.

**Comment by tomkralidis** [comment] 2015-06-13 01:40
@kevinpdavies thanks for the in depth analysis.  I'm seeing the same thing here.

@capooti: any ideas?  In GeoNode, pycsw was able to get a Layer's keywords with `ResourceBase.keyword_csv`.  Note we use `ResourceBase` so pycsw can exporse all GeoNode resources (not just layers).

Sounds like something we need to update in GeoNode.

**Comment by capooti** [comment] 2015-06-16 09:43
sure. I will have a look at this in the next few days and get back to you here.

**Comment by capooti** [comment] 2015-06-19 13:59
it looks like you need to get the keyword using layer as a content type, and not resourcebase. GeoNode keywords are associated to concrete classes (layers, maps, documents) and not to the base class (resourcebase), as far as I can remember

**Comment by capooti** [comment] 2015-06-19 14:03
yes, confirmed, is a bug in GN, I will send a fix for this.
Here is the actual code: https://github.com/GeoNode/geonode/blob/master/geonode/base/models.py#L399

We need to retrieve keywords using self.layer.keywords.all() / self.map.keywords.all() / self.document.all()

/cc @simod

**Comment by simod** [comment] 2015-06-19 14:06
@capooti right!. self.get_self_resource().keywords.all() should solve right?

**Comment by capooti** [comment] 2015-06-19 14:07
exactly. I'll send a PR right now
cheers
p

On Fri, Jun 19, 2015 at 4:06 PM, Simone Dalmasso <notifications@github.com>
wrote:

> @capooti <https://github.com/capooti> right!.
> self.get_self_resource().keywords.all() should solve right?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/geopython/pycsw/issues/339#issuecomment-113525675>.
>



-- 
Paolo Corti
Geospatial software developer
web: http://www.paolocorti.net
twitter: @capooti
skype: capooti

**Comment by tomkralidis** [comment] 2015-06-19 14:13
Thanks @capooti for tracking this down.  I'm guessing this should also be applied to https://github.com/GeoNode/geonode/blob/master/geonode/base/models.py#L378 https://github.com/GeoNode/geonode/blob/master/geonode/base/models.py#L381

**Comment by capooti** [comment] 2015-06-19 14:16
the problem is with django-polymorphic and it is opposite to what simod
says.

If you access it to the layer instance, then keywords are populated.
If you access it to the base instance, then keywords are not populated.

sample code:
from geonode.layers.models import Layer
lyr = Layer.objects.all()[0]
lyr.keywords.all()
[<Tag: flood>, <Tag: malawi>]
rb = lyr.get_self_resource()
ipdb> rb.keywords.all()

therefore client code need to access the concrete class, and not resource
base.


On Fri, Jun 19, 2015 at 4:07 PM, Paolo Corti <pcorti@gmail.com> wrote:

> exactly. I'll send a PR right now
> cheers
> p
>
> On Fri, Jun 19, 2015 at 4:06 PM, Simone Dalmasso <notifications@github.com
> > wrote:
>
>> @capooti <https://github.com/capooti> right!.
>> self.get_self_resource().keywords.all() should solve right?
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/geopython/pycsw/issues/339#issuecomment-113525675>.
>>
>
>
>
> --
> Paolo Corti
> Geospatial software developer
> web: http://www.paolocorti.net
> twitter: @capooti
> skype: capooti
>



-- 
Paolo Corti
Geospatial software developer
web: http://www.paolocorti.net
twitter: @capooti
skype: capooti

**Comment by simod** [comment] 2015-06-19 14:19
Ops right it is the other way around. Can polymorphic do that?

Il venerdì 19 giugno 2015, Paolo Corti <notifications@github.com> ha
scritto:

> the problem is with django-polymorphic and it is opposite to what simod
> says.
>
> If you access it to the layer instance, then keywords are populated.
> If you access it to the base instance, then keywords are not populated.
>
> sample code:
> from geonode.layers.models import Layer
> lyr = Layer.objects.all()[0]
> lyr.keywords.all()
> [<Tag: flood>, <Tag: malawi>]
> rb = lyr.get_self_resource()
> ipdb> rb.keywords.all()
>
> therefore client code need to access the concrete class, and not resource
> base.
>
>
> On Fri, Jun 19, 2015 at 4:07 PM, Paolo Corti <pcorti@gmail.com
> <javascript:_e(%7B%7D,'cvml','pcorti@gmail.com');>> wrote:
>
> > exactly. I'll send a PR right now
> > cheers
> > p
> >
> > On Fri, Jun 19, 2015 at 4:06 PM, Simone Dalmasso <
> notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>
> > > wrote:
> >
> >> @capooti <https://github.com/capooti> right!.
> >> self.get_self_resource().keywords.all() should solve right?
> >>
> >> —
> >> Reply to this email directly or view it on GitHub
> >> <https://github.com/geopython/pycsw/issues/339#issuecomment-113525675>.
> >>
> >
> >
> >
> > --
> > Paolo Corti
> > Geospatial software developer
> > web: http://www.paolocorti.net
> > twitter: @capooti
> > skype: capooti
> >
>
>
>
> --
> Paolo Corti
> Geospatial software developer
> web: http://www.paolocorti.net
> twitter: @capooti
> skype: capooti
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/geopython/pycsw/issues/339#issuecomment-113528454>.
>


-- 
Simone

**Comment by capooti** [comment] 2015-06-19 14:50
actually, as suggested by @tomkralidis in the chat, cannot figure out why django-polymorphic does not ties the keywords to the resourcebase class (also in the database).
Would make things easier for sure!

**Comment by tomkralidis** [comment] 2015-06-19 21:08
What is also puzzling is that one get access other ResourceBase fields like this, but not keywords.

**Comment by tomkralidis** [comment] 2015-06-20 01:16
@capooti @simod I found the below alternatives work:

```python
# instead of this
keywords_qs = self.keywords.all()
# this works
keywords_qs = self.get_real_concrete_instance_class().keywords.all()
# this works too
keywords_qs = self.get_real_instance().keywords.all()
# this works too
keywords_qs = self.get_real_instance_class().keywords.all()
```
Any comments?  Is there a preferred method to use?

**Comment by simod** [comment] 2015-06-20 20:38
@tomkralidis, thanks. I think that the "preferred" way is the
get_real_instance :)

2015-06-20 3:16 GMT+02:00 Tom Kralidis <notifications@github.com>:

> @capooti <https://github.com/capooti> @simod <https://github.com/simod> I
> found the below alternatives work:
>
> # instead of this
> keywords_qs = self.keywords.all()# this works
> keywords_qs = self.get_real_concrete_instance_class().keywords.all()# this works too
> keywords_qs = self.get_real_instance().keywords.all()# this works too
> keywords_qs = self.get_real_instance_class().keywords.all()
>
> Any comments? Is there a preferred method to use?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/geopython/pycsw/issues/339#issuecomment-113690615>.
>



-- 
Simone

**Comment by tomkralidis** [comment] 2015-06-21 19:44
@kevinpdavies FYI this is now fixed in GeoNode master.  Let me know if this works for you.  Thanks!

**Comment by capooti** [comment] 2015-06-22 07:49
thanks @tomkralidis and @simod, now it is working well in botch case
(accessing as real instance or as resourcebase).
excellent :)


On Sun, Jun 21, 2015 at 9:44 PM, Tom Kralidis <notifications@github.com>
wrote:

> @kevinpdavies <https://github.com/kevinpdavies> FYI this is now fixed in
> GeoNode master. Let me know if this works for you. Thanks!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/geopython/pycsw/issues/339#issuecomment-113948457>.
>



-- 
Paolo Corti
Geospatial software developer
web: http://www.paolocorti.net
twitter: @capooti
skype: capooti

**Closed** 2015-07-09 17:24 UTC
